name: sendtrain
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.02+3

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0


  cupertino_icons: ^1.0.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  google_sign_in: ^7.1.0
  sign_in_with_apple: ^7.0.1
  fl_chart: ^1.0.0
  dots_indicator: ^4.0.1
  cloud_functions: ^5.0.1
  flutter_local_notifications: ^19.3.0
  material_symbols_icons: ^4.2815.1
  timezone: ^0.10.1
  purchases_flutter: ^8.10.5
  purchases_ui_flutter: ^8.10.5
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  freezed_annotation: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/screens/
    - .env
